SCREEN_HEIGHT = 780
SCREEN_WIDTH = 640

ENEMY_WIDTH = 106
ENEMY_HEIGHT = 55

ENEMY_VERTICAL_LIMIT = 390
ENEMY_LOW_SHOOT_SPEED = 210
ALIEN_HIGH_SHOOT_SPEED = 100
SP_HIGH_SHOOT_SPEED = 130

LASER_HIGH_SPEED_BOOST = 3
LASER_BASE_SPEED = 3

GREEN_ENEMY_HP = 10
YELLOW_ENEMY_HP = 20
RED_ENEMY_HP = 40
SP_ENEMY_HP = 21

LOW_OVERHEAT = 1
MEDIUM_OVERHEAT = 2
HIGH_OVERHEAT = 4

MENU_MUSIC = 'Source/music/msc_01_menu.ogg'
FIGHT_MUSIC = 'Source/music/msc_02_wave_fight.ogg'
GAME_OVER_MUSIC = 'Source/music/msc_03_game_over.ogg'
ANGUILLE_INTRO_MUSIC = 'Source/music/msc_04_anguille_boss_intro.ogg'
ANGUILLE_FIGHT_MUSIC = 'Source/music/msc_05_anguille_boss_loop.ogg'
ROBOBOSS_INTRO_MUSIC = 'Source/music/msc_08_roboboss_intro.ogg'
ROBOBOSS_FIGHT_MUSIC = 'Source/music/msc_09_roboboss_loop.ogg'

MAIN_MENU_MARGIN = 215
PAUSE_MENU_MARGIN = 170

SAVE_PATH = "Source/Save/save.ppsave"

ANGUILLE_LAZER_SPEED = 13

SIDE_PUNCH_SPEED = 20

VITESSE_CDP = 12
